# Configuração do Pre-Commit com GitGuardian
# Este arquivo configura o ggshield para bloquear commits com segredos

repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.21.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
        
  # Hook adicional para escanear antes do push (opcional)
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.21.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-push]

